load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "helm_utils",
    srcs = ["helm_utils.go"],
    importpath = "github.com/periareon/rules_helm/helm/private/helm_utils",
    visibility = ["//helm:__subpackages__"],
    deps = [
        "@rules_go//go/runfiles",
    ],
)

go_test(
    name = "helm_utils_test",
    srcs = ["helm_utils_test.go"],
    embed = [":helm_utils"],
    deps = ["@rules_go//go/runfiles"],
)
